services:
  postgres:
    image: 'postgres:16'
    environment:
      POSTGRES_DB: agro_parcelles_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456789
    ports:
      - '5433:5432'
    volumes:
      - pgdata_parcelles:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d agro_parcelles_db']
      interval: 10s
      timeout: 5s
      retries: 5

  agro-parcelles:
    build: .
    ports:
      - '8082:8082'
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/agro_parcelles_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456789
      AUTH_SERVICE_URL: http://agro-auth:8081
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pgdata_parcelles: